AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB tables for OnPoint Admin Authentication System'

Parameters:
  Environment:
    Type: String
    Default: 'sandbox'
    AllowedValues: ['sandbox', 'prod']
    Description: 'Environment name'

Resources:
  # Tabla para usuarios del sistema
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'OnPointAdmin-Users-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: Authentication
        - Key: Project
          Value: OnPointAdmin

  # Tabla para tokens de verificación
  VerificationTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'OnPointAdmin-VerificationTokens-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: token
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        - AttributeName: expiresAt
          AttributeType: S
      KeySchema:
        - AttributeName: token
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TypeIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: expiresAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: Authentication
        - Key: Project
          Value: OnPointAdmin

  # Tabla para sesiones activas
  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'OnPointAdmin-Sessions-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: expiresAt
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: expiresAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: Authentication
        - Key: Project
          Value: OnPointAdmin

  # Tabla para códigos 2FA
  TwoFACodesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'OnPointAdmin-TwoFACodes-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: code
          AttributeType: S
        - AttributeName: expiresAt
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: code
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: CodeIndex
          KeySchema:
            - AttributeName: code
              KeyType: HASH
            - AttributeName: expiresAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: Authentication
        - Key: Project
          Value: OnPointAdmin

Outputs:
  UsersTableName:
    Description: 'Name of the Users table'
    Value: !Ref UsersTable
    Export:
      Name: !Sub '${Environment}-UsersTable'

  VerificationTokensTableName:
    Description: 'Name of the VerificationTokens table'
    Value: !Ref VerificationTokensTable
    Export:
      Name: !Sub '${Environment}-VerificationTokensTable'

  SessionsTableName:
    Description: 'Name of the Sessions table'
    Value: !Ref SessionsTable
    Export:
      Name: !Sub '${Environment}-SessionsTable'

  TwoFACodesTableName:
    Description: 'Name of the TwoFACodes table'
    Value: !Ref TwoFACodesTable
    Export:
      Name: !Sub '${Environment}-TwoFACodesTable'
