name: Deploy to Production

on:
  push:
    branches: [ main, production ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production

env:
  AWS_REGION: us-east-1
  STAGE: prod
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - name: Run tests (CI verbose)
        env:
          NODE_ENV: test
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          npm run test -- --ci --runInBand --verbose --json --outputFile=jest-results.json || true
          # Falla el job si Jest reporta failures
          if jq '.success' jest-results.json | grep -q 'true'; then
            echo "✅ Tests passed"
          else
            echo "❌ Tests failed" && exit 1
          fi

      - name: Upload Jest Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: jest-results.json

      - name: Run security audit (prod)
        run: |
          # Auditoría enfocada en prod deps
          npm audit --omit=dev --audit-level=high || true
          # Fallar solo si encuentra HIGH/CRITICAL en prod deps
          npm audit --omit=dev --json --audit-level=high > audit.json || true
          if jq '.metadata.vulnerabilities.high + .metadata.vulnerabilities.critical' audit.json | grep -q '^[1-9]'; then
            echo "❌ Vulnerabilidades HIGH/CRITICAL en dependencias de producción" && cat audit.json && exit 1
          else
            echo "✅ Auditoría sin HIGH/CRITICAL en prod"
          fi
      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: audit.json

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files-prod
          path: .next/

  deploy-lambda:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Lambda functions
        run: |
          echo "🚀 Desplegando Lambda functions a producción..."
          chmod +x scripts/deploy-lambda-functions.sh
          ./scripts/deploy-lambda-functions.sh prod

      - name: Update API Gateway
        run: |
          echo "🌐 Actualizando API Gateway..."
          chmod +x scripts/setup-api-gateway-prod.sh
          ./scripts/setup-api-gateway-prod.sh

      - name: Run health checks
        run: |
          echo "🏥 Ejecutando health checks..."
          chmod +x scripts/run-health-checks.sh
          ./scripts/run-health-checks.sh prod

  deploy-frontend:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          echo "📦 Desplegando frontend a S3..."
          aws s3 sync .next/static s3://onpoint-admin-prod/static --delete
          aws s3 sync public s3://onpoint-admin-prod/ --delete

      - name: Invalidate CloudFront
        run: |
          echo "🔄 Invalidando CloudFront..."
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

  notify:
    needs: [deploy-lambda, deploy-frontend]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check deployment status
        run: |
          echo "🔍 Verificando estado del despliegue..."
          echo "Lambda deployment: ${{ needs.deploy-lambda.result }}"
          echo "Frontend deployment: ${{ needs.deploy-frontend.result }}"
          
          if [ "${{ needs.deploy-lambda.result }}" == "success" ] && [ "${{ needs.deploy-frontend.result }}" == "success" ]; then
            echo "✅ Despliegue a producción completado exitosamente"
            echo "🚀 Sistema listo para producción"
          elif [ "${{ needs.deploy-lambda.result }}" == "skipped" ] && [ "${{ needs.deploy-frontend.result }}" == "skipped" ]; then
            echo "⚠️ Despliegue omitido (no es branch main o production)"
          else
            echo "❌ Despliegue a producción falló"
            echo "Lambda: ${{ needs.deploy-lambda.result }}"
            echo "Frontend: ${{ needs.deploy-frontend.result }}"
            exit 1
          fi
